In [1]:
import pandas as pd
import numpy as np

In [4]:
train = pd.read_csv("solicitudes_train.csv")
test = pd.read_csv("solicitudes_test.csv")
cbanco = pd.read_csv("comportamiento_bancario.csv")

In [5]:
print("train", train.shape)
print("test", test.shape)
print("cbanco", cbanco.shape)

train (32416, 8)
test (3061, 7)
cbanco (661139, 4)

In [8]:
train.head()

,ID_Solicitud,ID_Usuario,Monto_Solicitado,Tasa_Interes,Ingreso_Mensual,Motivo_Prestamo,Fecha_Solicitud,Estado_Final
0,1,12698,7900,0.2333,4461,Consumo,2025-04,1
1,2,20744,17400,0.2507,3889,Vivienda,2025-12,1
2,3,6830,8600,0.2368,4035,Vehiculo,2025-06,0
3,4,5722,13300,0.2826,4018,Vehiculo,2025-07,1
4,5,24719,6600,0.2314,3357,Otros,2025-01,1

In [9]:
test.head()

,ID_Solicitud,ID_Usuario,Monto_Solicitado,Tasa_Interes,Ingreso_Mensual,Motivo_Prestamo,Fecha_Solicitud
0,32417,27074,2300,0.2771,2596,Consumo,2026-01
1,32418,28172,10900,0.3291,6905,Consumo,2026-01
2,32419,27547,1300,0.2485,3707,Educacion,2026-01
3,32420,27689,1600,0.2699,3314,Consumo,2026-01
4,32421,26219,900,0.2317,3870,Educacion,2026-01

In [10]:
cbanco.head()

   ID_Usuario Mes_Referencia  Saldo_Promedio_Mensual  Dias_Atraso_Otras_Deudas
0           1        2024-01                12768.11                         3
1           1        2024-02                15817.67                         3
2           1        2024-03                13138.66                         0
3           1        2024-04                19453.13                         0
4           1        2024-05                14943.44                        59

In [11]:
train.describe()

,ID_Solicitud,ID_Usuario,Monto_Solicitado,Tasa_Interes,Ingreso_Mensual,Estado_Final
count,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000,32416.000000
mean,16208.500000,13008.947372,14290.097483,0.259580,4214.475938,0.840480
std,9357.837499,7464.560523,12995.295179,0.032333,2498.904569,0.366166
min,1.000000,1.000000,500.000000,0.147600,353.000000,0.000000
25%,8104.750000,6552.000000,5700.000000,0.237300,2481.000000,1.000000
50%,16208.500000,12996.500000,10200.000000,0.258300,3621.000000,1.000000
75%,24312.250000,19426.000000,18100.000000,0.280600,5276.000000,1.000000
max,32416.000000,25931.000000,70000.000000,0.379900,22000.000000,1.000000

In [12]:
test.describe()

,ID_Solicitud,ID_Usuario,Monto_Solicitado,Tasa_Interes,Ingreso_Mensual
count,3061.000000,3061.000000,3061.000000,3061.000000,3061.000000
mean,33947.000000,27463.000000,2235.315256,0.258836,4243.635413
std,883.778913,883.778913,2038.906892,0.032120,2516.618888
min,32417.000000,25933.000000,500.000000,0.164500,493.000000
25%,33182.000000,26698.000000,900.000000,0.237300,2500.000000
50%,33947.000000,27463.000000,1600.000000,0.257900,3660.000000
75%,34712.000000,28228.000000,2800.000000,0.279300,5303.000000
max,35477.000000,28993.000000,10900.000000,0.370200,20209.000000

In [13]:
cbanco.describe()

          ID_Usuario  Saldo_Promedio_Mensual  Dias_Atraso_Otras_Deudas
count  661139.000000           661139.000000             661139.000000
mean    14492.824615             5463.296614                  8.950755
std      8368.125761             5473.861364                 13.199638
min         1.000000                3.300000                  0.000000
25%      7247.000000             2061.955000                  1.000000
50%     14489.000000             3974.280000                  5.000000
75%     21739.000000             7082.925000                 10.000000
max     28993.000000           165915.350000                 90.000000

In [14]:
train.dtypes

ID_Solicitud          int64
ID_Usuario            int64
Monto_Solicitado      int64
Tasa_Interes        float64
Ingreso_Mensual       int64
Motivo_Prestamo      object
Fecha_Solicitud      object
Estado_Final          int64
dtype: object

In [15]:
test.dtypes

ID_Solicitud          int64
ID_Usuario            int64
Monto_Solicitado      int64
Tasa_Interes        float64
Ingreso_Mensual       int64
Motivo_Prestamo      object
Fecha_Solicitud      object
dtype: object

In [16]:
cbanco.dtypes

ID_Usuario                    int64
Mes_Referencia               object
Saldo_Promedio_Mensual      float64
Dias_Atraso_Otras_Deudas      int64
dtype: object

In [17]:
train.isnull().sum()

ID_Solicitud        0
ID_Usuario          0
Monto_Solicitado    0
Tasa_Interes        0
Ingreso_Mensual     0
Motivo_Prestamo     0
Fecha_Solicitud     0
Estado_Final        0
dtype: int64

In [18]:
test.isnull().sum()

ID_Solicitud        0
ID_Usuario          0
Monto_Solicitado    0
Tasa_Interes        0
Ingreso_Mensual     0
Motivo_Prestamo     0
Fecha_Solicitud     0
dtype: int64

In [19]:
cbanco.isnull().sum()

ID_Usuario                  0
Mes_Referencia              0
Saldo_Promedio_Mensual      0
Dias_Atraso_Otras_Deudas    0
dtype: int64

In [21]:
train.select_dtypes(include="object").nunique()

Motivo_Prestamo     7
Fecha_Solicitud    12
dtype: int64

In [22]:
train.corr(numeric_only=True)

,ID_Solicitud,ID_Usuario,Monto_Solicitado,Tasa_Interes,Ingreso_Mensual,Estado_Final
ID_Solicitud,1.000000,-0.004156,0.005806,-0.006257,0.004769,0.003554
ID_Usuario,-0.004156,1.000000,-0.019080,-0.008992,-0.010518,0.018095
Monto_Solicitado,0.005806,-0.019080,1.000000,0.501011,0.595346,-0.100268
Tasa_Interes,-0.006257,-0.008992,0.501011,1.000000,-0.013449,-0.112172
Ingreso_Mensual,0.004769,-0.010518,0.595346,-0.013449,1.000000,0.007362
Estado_Final,0.003554,0.018095,-0.100268,-0.112172,0.007362,1.000000

In [27]:
train.duplicated().sum()

0

In [28]:
test.duplicated().sum()

0

In [29]:
cbanco.duplicated().sum()

0

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression

In [31]:
train_modelo = train.copy()
test_modelo = test.copy()
banco_modelo = cbanco.copy()

In [32]:
train_modelo["Fecha_Solicitud"] = train_modelo["Fecha_Solicitud"].astype(str)
test_modelo["Fecha_Solicitud"] = test_modelo["Fecha_Solicitud"].astype(str)
banco_modelo["Mes_Referencia"] = banco_modelo["Mes_Referencia"].astype(str)

In [33]:
def agregarHistorialBancario(solicitudes, historial):
    datos = solicitudes[
        ["ID_Solicitud", "ID_Usuario", "Fecha_Solicitud"]
    ].join(
        historial.set_index("ID_Usuario"),
        on="ID_Usuario",
        how="left"
    )
    datos = datos[
        datos["Mes_Referencia"] < datos["Fecha_Solicitud"]
    ]

    resumen = []
    for id_solicitud in solicitudes["ID_Solicitud"].unique():
        grupo = datos[datos["ID_Solicitud"] == id_solicitud]

        saldo_promedio = grupo["Saldo_Promedio_Mensual"].mean()
        saldo_minimo = grupo["Saldo_Promedio_Mensual"].min()
        saldo_maximo = grupo["Saldo_Promedio_Mensual"].max()

        atraso_promedio = grupo["Dias_Atraso_Otras_Deudas"].mean()
        atraso_maximo = grupo["Dias_Atraso_Otras_Deudas"].max()

        meses_historial = grupo["Mes_Referencia"].nunique()

        resumen.append({
            "ID_Solicitud": id_solicitud,
            "saldo_promedio": saldo_promedio,
            "saldo_minimo": saldo_minimo,
            "saldo_maximo": saldo_maximo,
            "atraso_promedio": atraso_promedio,
            "atraso_maximo": atraso_maximo,
            "meses_historial": meses_historial
        })
    resumen = pd.DataFrame(resumen)
    resumen = resumen.set_index("ID_Solicitud")
    
    resultado = solicitudes.join(
        resumen,
        on="ID_Solicitud",
        how="left"
    )
    return resultado
train_preparado = agregarHistorialBancario(train_modelo, banco_modelo)
test_preparado = agregarHistorialBancario(test_modelo, banco_modelo)

In [34]:
train_preparado.shape

(32416, 14)

In [35]:
test_preparado.shape

(3061, 13)

In [36]:
train_preparado.isnull().sum()

ID_Solicitud        0
ID_Usuario          0
Monto_Solicitado    0
Tasa_Interes        0
Ingreso_Mensual     0
Motivo_Prestamo     0
Fecha_Solicitud     0
Estado_Final        0
saldo_promedio      0
saldo_minimo        0
saldo_maximo        0
atraso_promedio     0
atraso_maximo       0
meses_historial     0
dtype: int64

In [37]:
train_preparado.head()

,ID_Solicitud,ID_Usuario,Monto_Solicitado,Tasa_Interes,Ingreso_Mensual,Motivo_Prestamo,Fecha_Solicitud,Estado_Final,saldo_promedio,saldo_minimo,saldo_maximo,atraso_promedio,atraso_maximo,meses_historial
0,1,12698,7900,0.2333,4461,Consumo,2025-04,1,3695.225714,3121.25,4698.37,4.857143,25,14
1,2,20744,17400,0.2507,3889,Vivienda,2025-12,1,5976.456667,3807.48,7011.74,8.809524,56,21
2,3,6830,8600,0.2368,4035,Vehiculo,2025-06,0,178.574667,154.88,209.05,20.733333,57,15
3,4,5722,13300,0.2826,4018,Vehiculo,2025-07,1,7589.356667,5949.24,9501.68,0.944444,4,18
4,5,24719,6600,0.2314,3357,Otros,2025-01,1,3888.616667,2952.59,4848.48,3.750000,32,12

In [38]:
entrenamiento = train_preparado[
    train_preparado["Fecha_Solicitud"] < "2025-11"
].copy()

validacion = train_preparado[
    train_preparado["Fecha_Solicitud"] >= "2025-11"
].copy()

In [39]:
print("Solicitudes entrenar:", len(entrenamiento))
print("Solicitudes validar:", len(validacion))

Solicitudes entrenar: 27106
Solicitudes validar: 5310

In [42]:
print("\nMeses entrenamiento:")
print(entrenamiento[["Fecha_Solicitud"]].drop_duplicates().sort_values("Fecha_Solicitud"))

print("\nMeses validación:")
print(validacion[["Fecha_Solicitud"]].drop_duplicates().sort_values("Fecha_Solicitud"))

Meses entrenamiento:
   Fecha_Solicitud
4          2025-01
6          2025-02
9          2025-03
0          2025-04
8          2025-05
2          2025-06
3          2025-07
30         2025-08
12         2025-09
13         2025-10

Meses validación:
   Fecha_Solicitud
19         2025-11
1          2025-12

In [43]:
print("\nProporción pagos entrenamiento:")
print(entrenamiento["Estado_Final"].mean())

print("\nProporción pagos validación:")
print(validacion["Estado_Final"].mean())

Proporción pagos entrenamiento:
0.8394820334981185

Proporción pagos validación:
0.8455743879472694

In [44]:
columnas_numericas = [
    "Monto_Solicitado",
    "Tasa_Interes",
    "Ingreso_Mensual",
    "saldo_promedio",
    "saldo_minimo",
    "saldo_maximo",
    "atraso_promedio",
    "atraso_maximo",
    "meses_historial"
]
columnas_categoricas = ["Motivo_Prestamo"]
columnas_modelo = columnas_numericas + columnas_categoricas

X_entrenamiento = entrenamiento[columnas_modelo]
y_entrenamiento = entrenamiento["Estado_Final"]

X_validacion = validacion[columnas_modelo]
y_validacion = validacion["Estado_Final"]

print("Variables entrada:", columnas_modelo)
print("X_entrenamiento:", X_entrenamiento.shape)
print("X_validacion:", X_validacion.shape)

Variables entrada: ['Monto_Solicitado', 'Tasa_Interes', 'Ingreso_Mensual', 'saldo_promedio', 'saldo_minimo', 'saldo_maximo', 'atraso_promedio', 'atraso_maximo', 'meses_historial', 'Motivo_Prestamo']
X_entrenamiento: (27106, 10)
X_validacion: (5310, 10)

In [47]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])
preprocessor = ColumnTransformer([
    ("numericas", numeric_pipeline, columnas_numericas),
    ("categoricas", categorical_pipeline, columnas_categoricas)
])
modelo = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        random_state=42
    ))
])

modelo.fit(X_entrenamiento, y_entrenamiento)

print("Modelo entrenado correctamente")

Modelo entrenado correctamente

In [49]:
from sklearn.metrics import roc_auc_score, accuracy_score, classification_report
probabilidades_validacion = modelo.predict_proba(
    X_validacion
)[:, 1]

predicciones_validacion = (
    probabilidades_validacion >= 0.5
).astype(int)

auc = roc_auc_score(
    y_validacion,
    probabilidades_validacion
)

accuracy = accuracy_score(
    y_validacion,
    predicciones_validacion
)

print("AUC:", auc)
print("Accuracy:",accuracy)

print("\nReporte de clasificación:")
print(classification_report(
    y_validacion,
    predicciones_validacion,
    target_names=["Incumple (0)", "Paga (1)"]
))

AUC: 0.842126133956217
Accuracy: 0.7766478342749529

Reporte de clasificación:
              precision    recall  f1-score   support

Incumple (0)       0.39      0.76      0.51       820
    Paga (1)       0.95      0.78      0.86      4490

    accuracy                           0.78      5310
   macro avg       0.67      0.77      0.68      5310
weighted avg       0.86      0.78      0.80      5310

In [50]:
resultados = validacion[
    ["ID_Solicitud", "Monto_Solicitado", "Tasa_Interes", "Estado_Final"]
].copy()

resultados["Probabilidad_Pago"] = probabilidades_validacion

resultados["Ganancia_Esperada"] = (
    resultados["Probabilidad_Pago"]
    * resultados["Monto_Solicitado"]
    * resultados["Tasa_Interes"]
    - (1 - resultados["Probabilidad_Pago"])
    * resultados["Monto_Solicitado"]
)

resultados["Rendimiento"] = (
    resultados["Ganancia_Esperada"]
    / resultados["Monto_Solicitado"]
)

print("Resultados:")
display(resultados.head())

Resultados:

,ID_Solicitud,Monto_Solicitado,Tasa_Interes,Estado_Final,Probabilidad_Pago,Ganancia_Esperada,Rendimiento
1,2,17400,0.2507,1,0.746322,-1158.408734,-0.066575
5,6,7100,0.2663,1,0.760969,-258.330613,-0.036385
11,12,22500,0.2964,1,0.782351,320.394375,0.014240
15,16,10700,0.2531,1,0.846676,652.375413,0.060970
19,20,13400,0.2907,1,0.675942,-1709.329445,-0.127562

In [51]:
candidatos = resultados[
    resultados["Ganancia_Esperada"] > 0
].sort_values("Rendimiento", ascending=False)

presupuesto = 2_000_000
capital_usado = 0
indices_aprobados = []

for indice in candidatos.index:
    monto = candidatos.loc[indice, "Monto_Solicitado"]

    if capital_usado + monto <= presupuesto:
        indices_aprobados.append(indice)
        capital_usado += monto

aprobados_validacion = resultados.loc[indices_aprobados].copy()

print("Cantidad de préstamos aprobados:", len(aprobados_validacion))
print("Capital utilizado: $", capital_usado)
print("Presupuesto restante: $", presupuesto - capital_usado)

Cantidad de préstamos aprobados: 91
Capital utilizado: $ 1999600
Presupuesto restante: $ 400

In [52]:
aprobados_validacion["Ganancia_Real"] = 0.0
for i in range(len(aprobados_validacion)):
    if aprobados_validacion["Estado_Final"].iloc[i] == 1:
        aprobados_validacion.loc[
            aprobados_validacion.index[i], "Ganancia_Real"
        ] = (
            aprobados_validacion["Monto_Solicitado"].iloc[i]
            * aprobados_validacion["Tasa_Interes"].iloc[i]
        )
    else:
        aprobados_validacion.loc[
            aprobados_validacion.index[i], "Ganancia_Real"
        ] = -aprobados_validacion["Monto_Solicitado"].iloc[i]

ganancia_esperada_total = aprobados_validacion["Ganancia_Esperada"].sum()
ganancia_real_total = aprobados_validacion["Ganancia_Real"].sum()

porcentaje_pago = (
    aprobados_validacion["Estado_Final"].mean() * 100
    if len(aprobados_validacion) > 0
    else 0
)

print(f"Ganancia esperada: ${ganancia_esperada_total:,.2f}")
print(f"Ganancia real observada: ${ganancia_real_total:,.2f}")
print(f"Porcentaje de préstamos pagados: {porcentaje_pago:.2f}%")

Ganancia esperada: $479,617.40
Ganancia real observada: $521,627.57
Porcentaje de préstamos pagados: 98.90%

In [59]:
X = train_preparado[columnas_modelo]
y = train_preparado["Estado_Final"]

modelo_final = Pipeline([
    ("preprocessor", preprocessor),
    ("modelo_final", LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        random_state=42
    ))
])

modelo_final.fit(X, y)

print("Modelo entrenado.")
print("Solicitudes utilizadas:", len(X))

Modelo entrenado.
Solicitudes utilizadas: 32416

In [54]:
X_test = test_preparado[columnas_modelo]
probabilidades_test = modelo_final.predict_proba(X_test)[:, 1]

print("Cantidad de predicciones:", len(probabilidades_test))
print("Primeras 10 probabilidades:")
print(probabilidades_test[:10])

Cantidad de predicciones: 3061
Primeras 10 probabilidades:
[0.31103594 0.98560282 0.16593232 0.85038081 0.92980235 0.76442297
 0.93830002 0.64537314 0.48146236 0.11853957]

In [55]:
seleccion = test_preparado[
    ["ID_Solicitud", "Monto_Solicitado", "Tasa_Interes"]
].copy()

seleccion["Probabilidad_Pago"] = probabilidades_test

seleccion["Ganancia_Esperada"] = (
    seleccion["Probabilidad_Pago"]
    * seleccion["Monto_Solicitado"]
    * seleccion["Tasa_Interes"]
    - (1 - seleccion["Probabilidad_Pago"])
    * seleccion["Monto_Solicitado"]
)

seleccion["Rendimiento"] = (
    seleccion["Ganancia_Esperada"]
    / seleccion["Monto_Solicitado"]
)

candidatos = seleccion[
    seleccion["Ganancia_Esperada"] > 0
].sort_values("Rendimiento", ascending=False)

presupuesto = 2_000_000
capital_usado = 0
aprobados = []

for i in range(len(candidatos)):
    monto = candidatos["Monto_Solicitado"].iloc[i]
    id_solicitud = candidatos["ID_Solicitud"].iloc[i]

    if capital_usado + monto <= presupuesto:
        aprobados.append(id_solicitud)
        capital_usado += monto

print("Préstamos aprobados:", len(aprobados))
print("Capital utilizado: $", capital_usado)
print("Presupuesto restante: $", presupuesto - capital_usado)

Préstamos aprobados: 632
Capital utilizado: $ 1999900
Presupuesto restante: $ 100

In [57]:
submission_logistica = pd.DataFrame({
    "ID_Solicitud": test_preparado["ID_Solicitud"],
    "Decision_Aprobacion": (
        test_preparado["ID_Solicitud"]
        .isin(set(aprobados))
        .astype(int)
    )
})

submission_logistica.to_csv(
    "PrediccionRL.csv",
    index=False
)

print("Archivo creado: PrediccionRL.csv")

Archivo creado: PrediccionRL.csv

In [58]:
from IPython.display import FileLink, display
display(FileLink("PrediccionRL.csv"))

/home/trinidadbonzi/machine-learning/prestamatch/PrediccionRL.csv